# -*- coding: utf-8 -*-
"""Plotly_Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FsftT8g2hCHNrsjd3X9TWksXCBbf5s41
"""

import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x = [1,2,3,4,5], y = [3,4,5,6,7], mode = 'markers' ))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x = [1,2,3,4,5], y = [3,4,5,6,7], mode = 'lines' ))
fig.show()

fig = go.Figure()
fig.add_trace(go.Bar(x = [1,2,3,4,5], y = [3,4,5,6,7], ))
fig.show()

x = [1,2,3,4,6,4,9,7,9,2,12,3,1,56,45,6,8,96,7,6,7,67]
fig = go.Figure(data = go.Histogram(x = x))
fig.show()

import seaborn as sns

tips = sns.load_dataset("tips")

tips

fig = go.Figure(data = [go.Histogram(x =tips.total_bill)])
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill, y=tips.tip, mode = 'markers'))
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill, y=tips.tip, mode = 'markers',marker_size = 7*tips['size'] ))
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=tips.total_bill, y=tips.tip, mode = 'markers', z = 3*tips['size'] ))
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4], y=[5,6,7,8], mode = 'lines', z =[2,3,4,2] ))
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4], y=[5,6,7,8], mode = 'markers', z =[2,3,4,2] ))
fig.show()

import plotly.graph_objects
fig = go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill, y=tips.tip, mode = 'lines',marker_size = 7*tips['size'] ))
fig.show()

